### ISSUE TITLE
Recceiver fails to start

### ISSUE THREAD

**Issue by tanviash** [ChannelFinder/recsync#35]
@shengb 

I am seeing an issue where receiver fails to start at commit 7ebed83. I'm using Debian Jessie, Twisted 14.0.2, Python 2.7.9. It seems to be working before this commit. Has anything changed in the way recceiver is to be run (like python version)? @yifans reported a similar issue on his setup https://github.com/ChannelFinder/recsync/issues/34#issue-384802658

devuser@develop-vmphy0:~/recsync/server$ twistd -r poll -n recceiver -f demo.conf
Traceback (most recent call last):
  File "/usr/bin/twistd", line 14, in <module>
    run()
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 27, in run
    app.run(runApp, ServerOptions)
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 436, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/home/devuser/recsync/server/recceiver/application.py", line 112, in makeService
    ctrl = ProcessorController(cfile=opts['config'])
  File "/home/devuser/recsync/server/recceiver/processors.py", line 89, in __init__
    plug = plugs[plugname]
KeyError: 'show'

The steps I did were following. I did not have recceiver package installed on my system. 
git clone https://github.com/ChannelFinder/recsync.git
cd recsync/server
git reset --hard 7ebed83a9870d1343d0fcb359e28d6ffea1848f5
twistd -r poll -n recceiver -f demo.conf

**Comment by tanviash** [comment]
The problem seems to be coming from line 79 of processors.py. Code flow doesn't enter the for loop ' for plug in plugin.getPlugins(interfaces.IProcessorFactory):' which shows plugin info for the procs (show, cf & db) are not available. The issue is not seen on Debian Jessie (Twisted 14.0.2) , only seen on Debian Stretch (Twisted 16.6.0).

**Comment by shengb** [comment]
@tanviash 

Which twisted library are you using? 
Is it possible to try a new version, for example twistd 17.5.0?
That change has a update to a new twisted library. 

Here is output on my machine:
$ twistd -r poll -n recceiver -f demo.conf
2018-12-21T14:09:45-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/usr/local/bin/python 3.6.6) starting up.
2018-12-21T14:09:45-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.pollreactor.PollReactor.
2018-12-21T14:09:45-0600 [stdout#info] Starting
2018-12-21T14:09:45-0600 [-] CastFactory starting on 62127
2018-12-21T14:09:45-0600 [recceiver.recast.CastFactory#info] Starting factory <recceiver.recast.CastFactory object at 0x10c90c198>
2018-12-21T14:09:45-0600 [-] CastFactory starting on 62128
2018-12-21T14:09:45-0600 [stdout#info] listening on IPv4Address(TCP, '0.0.0.0', 62128)
2018-12-21T14:09:45-0600 [-] Announcer starting on 50491
2018-12-21T14:09:45-0600 [-] Starting protocol <recceiver.announce.Announcer object at 0x10c90c8d0>

**Comment by tanviash** [comment]
I tried on two setups - Debian Jessie, Twisted 14.0.2, Python 2.7.9 and Debian Stretch, Twisted 16.6.0, Python 2.7.13 and I see the same problem. Since I use Debain packages, I get twisted installed based on the default on these OS versions.

**Comment by tanviash** [comment]
However, things seem to work if I apply this diff on my twisted 14.0.2 setup. Can you pls try this diff and see if it is not breaking things for you?

devuser@develop-vmphy0:~/recsync/server$ git diff
diff --git a/server/recceiver/processors.py b/server/recceiver/processors.py
index d75719f..3bd23d9 100644
--- a/server/recceiver/processors.py
+++ b/server/recceiver/processors.py
@@ -143,8 +143,8 @@ class ShowProcessor(service.Service):
         _log.info('Show processor stopping') 
-@implementer(plugin.IPlugin)
-@provider(interfaces.IProcessorFactory)
+@implementer(plugin.IPlugin, interfaces.IProcessorFactory)
+#@provider(interfaces.IProcessorFactory)
 class ProcessorFactory(object):
     name = None
     processor = None

**Comment by shengb** [comment]
No, that does not work with for example twistd 17.5.0.

  File "//usr/local/develop/recsync/server/twisted/plugins/recceiver_plugin.py", line 3, in <module>
    from recceiver.application import Maker
  File "//usr/local/develop/recsync/server/recceiver/application.py", line 16, in <module>
    from .processors import ProcessorController
  File "//usr/local/develop/recsync/server/recceiver/processors.py", line 148, in <module>
    @Implementer(plugin.IPlugin, interfaces.IProcessorFactory)
exceptions.NameError: name 'Implementer' is not defined

**Comment by yifans** [comment]
@tanviash 
I have not solved this problem. I cloned it again and tried to start it, but I still saw the same error.

``` shell
yifans@YifanSong-Ubuntu:~/code$ uname -a
Linux YifanSong-Ubuntu 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
yifans@YifanSong-Ubuntu:~/code$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
yifans@YifanSong-Ubuntu:~/code$ python --version
Python 3.6.6 :: Anaconda, Inc.
yifans@YifanSong-Ubuntu:~/code$ twistd --version
twistd (the Twisted daemon) 18.9.0
Copyright (c) 2001-2018 Twisted Matrix Laboratories.
See LICENSE for details.
yifans@YifanSong-Ubuntu:~/code$ git clone https://github.com/ChannelFinder/recsync.git
Cloning into 'recsync'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 604 (delta 1), reused 2 (delta 1), pack-reused 591
Receiving objects: 100% (604/604), 144.82 KiB | 121.00 KiB/s, done.
Resolving deltas: 100% (360/360), done.
yifans@YifanSong-Ubuntu:~/code$ cd recsync/server/
yifans@YifanSong-Ubuntu:~/code/recsync/server$ ls
cf.conf  demo.conf  MANIFEST.in  README  recceiver  recceiver.sqlite3  setup.py  twisted
yifans@YifanSong-Ubuntu:~/code/recsync/server$ sqlite3 test.db -init recceiver.sqlite3 .exit
-- Loading resources from recceiver.sqlite3
yifans@YifanSong-Ubuntu:~/code/recsync/server$ export PYTHONPATH=.
yifans@YifanSong-Ubuntu:~/code/recsync/server$ cp demo.conf demo.conf.bak
yifans@YifanSong-Ubuntu:~/code/recsync/server$ vim demo.conf
yifans@YifanSong-Ubuntu:~/code/recsync/server$ diff demo.conf demo.conf.bak 
13c13
< addrlist = 127.255.255.255:5049
---
> #addrlist = 127.255.255.255:5049
66c66
< # debug_file_loc = /home/devuser/recsyncdata.txt
---
> # debug_file_loc = /home/devuser/recsyncdata.txt
\ No newline at end of file
yifans@YifanSong-Ubuntu:~/code/recsync/server$ twistd -r poll -n recceiver -f demo.conf
Usage: twistd [options]
Options:
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
      --chroot=        Chroot to a supplied directory before running
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
  -e, --encrypted      The specified tap/aos file is encrypted.
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -f, --file=          read the given .tap file [default: twistd.tap]
  -g, --gid=           The gid to run as.  If not specified, the default gid
                       associated with the specified --uid is used.
      --help           Display this help and exit.
      --help-reactors  Display a list of possibly available reactor names.
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
  -o, --no_save        do not save state on shutdown
      --originalname   Don't try to change the process name
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
  -s, --source=        Read an application from a .tas file (AOT format).
      --savestats      save the Stats object rather than the text output of the
                       profiler.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
      --syslog         Log to syslog, not to file
  -u, --uid=           The uid to run as.
      --umask=         The (octal) file creation mask to apply.
      --version        Print version information and exit.
  -y, --python=        read an application from within a Python file (implies
                       -o)

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch            A Conch SSH service.
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    manhole          An interactive remote debugger service accessible via
                     telnet and ssh and providing syntax coloring and basic line
                     editing functionality.
    portforward      A simple port-forwarder.
    procmon          A process watchdog / supervisor
    recceiver        RecCaster receiver server
    socks            A SOCKSv4 proxy service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.
    words            A modern words server
    xmpp-router      An XMPP Router server

/home/yifans/apps/Anaconda3/bin/twistd: The specified reactor cannot be used, failed with error: reactor already installed.
See the list of available reactors with --help-reactors
yifans@YifanSong-Ubuntu:~/code/recsync/server$ twistd -r poll -n recceiver -f demo.conf
Traceback (most recent call last):
  File "/home/yifans/apps/Anaconda3/bin/twistd", line 11, in <module>
    sys.exit(run())
  File "/home/yifans/apps/Anaconda3/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/home/yifans/apps/Anaconda3/lib/python3.6/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/home/yifans/apps/Anaconda3/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/home/yifans/apps/Anaconda3/lib/python3.6/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/home/yifans/apps/Anaconda3/lib/python3.6/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/home/yifans/code/recsync/server/recceiver/application.py", line 112, in makeService
    ctrl = ProcessorController(cfile=opts['config'])
  File "/home/yifans/code/recsync/server/recceiver/processors.py", line 89, in __init__
    plug = plugs[plugname]
KeyError: 'show ; just print'
```

**Comment by tanviash** [comment]
@shengb Please take a look at @yifans last comment. He sees the same problem with Twisted 18.9.

**Comment by shengb** [comment]
@tanviash @yifans 
Here are my results without modifying any code:
1. Ubuntu 16.04.4: 
Python 2.7.15 + twisted 17.5.0 + requests 2.18, it works
Python 3.6.7 + twisted 17.5.0 + requests 2.18, it does not.

2. on my Mac:
Python 3.6.6 + twisted 17.5.0, it works.

It seems that there are some problems for twisted on Linux working with Python3.6.

**Comment by shengb** [comment]
Do not know what happened. I just opened a fresh terminal, and it works now on my Ubuntu with Python 3.6.7 + twisted 17.5.0 + requests 2.18.

**Comment by shengb** [comment]
@tanviash @yifans 
Could you test it again with a fresh environment, for example a conda env, and let me know your results?
I tested with 3 different twisted versions, and all work fine.

Here are my examples:
1.
$ conda create -n recsync
$ conda activate recsync
$ conda install python=3.6 twisted=18.9 requests=2.18

2.
$ conda create -n recsync-twisted17.5
$ conda activate recsync-twisted17.5
$ conda install python=3.6 twisted=17.5 requests=2.18

3.
$ conda create -n recsync-twisted16.6
$ conda activate recsync-twisted16.6
$ conda install python=3.6 twisted=16.6 requests=2.18

and results for each test.
$ twistd -r poll -n recceiver -f demo.conf
2018-12-22T11:48:37-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/usr/local/conda/envs/recsync/bin/python 3.6.7) starting up.
2018-12-22T11:48:37-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.pollreactor.PollReactor.
2018-12-22T11:48:37-0600 [stdout#info] Starting
2018-12-22T11:48:37-0600 [-] CastFactory starting on 42727
2018-12-22T11:48:37-0600 [recceiver.recast.CastFactory#info] Starting factory <recceiver.recast.CastFactory object at 0x7f11e04cfba8>
2018-12-22T11:48:37-0600 [-] CastFactory starting on 42581
2018-12-22T11:48:37-0600 [stdout#info] listening on IPv4Address(type='TCP', host='0.0.0.0', port=42581)
2018-12-22T11:48:37-0600 [-] Announcer starting on 50239
2018-12-22T11:48:37-0600 [-] Starting protocol <recceiver.announce.Announcer object at 0x7f11e04de438>
^C2018-12-22T11:48:51-0600 [-] Received SIGINT, shutting down.
2018-12-22T11:48:51-0600 [-] (UDP Port 50239 Closed)
2018-12-22T11:48:51-0600 [-] Stopping protocol <recceiver.announce.Announcer object at 0x7f11e04de438>
2018-12-22T11:48:51-0600 [-] (TCP Port 42581 Closed)
2018-12-22T11:48:51-0600 [-] Main loop terminated.
2018-12-22T11:48:51-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

(recsync) test@recsyncvm:~/recsync/server$ twistd --version
twistd (the Twisted daemon) 18.9.0
Copyright (c) 2001-2018 Twisted Matrix Laboratories.
See LICENSE for details.
(recsync) test@recsyncvm:~/recsync/server$ python --version
Python 3.6.7 :: Anaconda, Inc.
(recsync) test@recsyncvm:~/recsync/server$ uname -a
Linux recsyncvm 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ sh start.sh 
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
2018-12-22T11:51:15-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/usr/local/conda/envs/recsync-twisted17.5/bin/python 3.6.7) starting up.
2018-12-22T11:51:15-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.pollreactor.PollReactor.
2018-12-22T11:51:15-0600 [stdout#info] Starting
2018-12-22T11:51:15-0600 [-] CastFactory starting on 38349
2018-12-22T11:51:15-0600 [recceiver.recast.CastFactory#info] Starting factory <recceiver.recast.CastFactory object at 0x7f4c416d4550>
2018-12-22T11:51:15-0600 [-] CastFactory starting on 35219
2018-12-22T11:51:15-0600 [stdout#info] listening on IPv4Address(TCP, '0.0.0.0', 35219)
2018-12-22T11:51:15-0600 [-] Announcer starting on 37604
2018-12-22T11:51:15-0600 [-] Starting protocol <recceiver.announce.Announcer object at 0x7f4c416d4780>
^C2018-12-22T11:51:18-0600 [-] Received SIGINT, shutting down.
2018-12-22T11:51:18-0600 [-] (UDP Port 37604 Closed)
2018-12-22T11:51:18-0600 [-] Stopping protocol <recceiver.announce.Announcer object at 0x7f4c416d4780>
2018-12-22T11:51:18-0600 [-] (TCP Port 35219 Closed)
2018-12-22T11:51:18-0600 [-] Main loop terminated.
2018-12-22T11:51:18-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

(recsync-twisted17.5) test@recsyncvm:~/recsync/server$ twistd --version
twistd (the Twisted daemon) 17.5.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
(recsync-twisted17.5) test@recsyncvm:~/recsync/server$ python --version
Python 3.6.7 :: Anaconda, Inc.
(recsync-twisted17.5) test@recsyncvm:~/recsync/server$ uname -a
Linux barkeria-vm3 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(recsync-twisted17.5) test@recsyncvm:~/recsync/server$ 

$ sh start.sh
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
2018-12-22T16:43:56-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.6.0 (/usr/local/conda/envs/recsync-twisted16.6/bin/python 3.6.7) starting up.
2018-12-22T16:43:56-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.pollreactor.PollReactor.
2018-12-22T16:43:56-0600 [stdout#info] Starting
2018-12-22T16:43:56-0600 [-] CastFactory starting on 43317
2018-12-22T16:43:56-0600 [recceiver.recast.CastFactory#info] Starting factory <recceiver.recast.CastFactory object at 0x7fa5970adcf8>
2018-12-22T16:43:56-0600 [-] CastFactory starting on 37121
2018-12-22T16:43:56-0600 [stdout#info] listening on IPv4Address(TCP, '0.0.0.0', 37121)
2018-12-22T16:43:56-0600 [-] Announcer starting on 54946
2018-12-22T16:43:56-0600 [-] Starting protocol <recceiver.announce.Announcer object at 0x7fa5970b68d0>
^C2018-12-22T16:44:11-0600 [-] Received SIGINT, shutting down.
2018-12-22T16:44:11-0600 [-] (UDP Port 54946 Closed)
2018-12-22T16:44:11-0600 [-] Stopping protocol <recceiver.announce.Announcer object at 0x7fa5970b68d0>
2018-12-22T16:44:11-0600 [-] (TCP Port 37121 Closed)
2018-12-22T16:44:11-0600 [-] Main loop terminated.
2018-12-22T16:44:11-0600 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

(recsync-twisted16.6) test@recsyncvm:~/recsync/server$ twistd --version
twistd (the Twisted daemon) 16.6.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
(recsync-twisted16.6) test@recsyncvm:~/recsync/server$ python --version
Python 3.6.7 :: Anaconda, Inc.
(recsync-twisted16.6) test@recsyncvm:~/recsync/server$ uname -a
Linux recsyncvm 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mdavidsaver** [comment]
> +@Implementer(plugin.IPlugin, interfaces.IProcessorFactory)

This is the correct change (9a19ad39bc209e74a79c7742672194d2aae4ccc7).  I'm not sure why this worked before or what changed.  IPlugin is my least favorite aspect of twisted.

**Comment by mdavidsaver** [comment]
> Do not know what happened

The best advise I can give (aside from not using IPlugin any further) is to frequently delete `twisted/plugins/dropin.cache` as well as the python bytecode cache files in this directory.

Also, I am able to run `demo.conf` with python 3.5 and twisted 16.6.

**Comment by yifans** [comment]
@mdavidsaver  The last submitted code is working fine here, no errors, thanks for your work.

``` shell
➜  /Users/yifans/code/recsync/server git:(master) ✗ twistd -r poll -n recceiver -f demo.conf
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
2018-12-24T23:08:05+0800 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/Users/yifans/anaconda/bin/python 3.6.3) starting up.
2018-12-24T23:08:05+0800 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.pollreactor.PollReactor.
2018-12-24T23:08:05+0800 [stdout#info] Starting
2018-12-24T23:08:05+0800 [-] CastFactory starting on 50266
2018-12-24T23:08:05+0800 [recceiver.recast.CastFactory#info] Starting factory <recceiver.recast.CastFactory object at 0x108624048>
2018-12-24T23:08:05+0800 [-] CastFactory starting on 50267
2018-12-24T23:08:05+0800 [stdout#info] listening on IPv4Address(TCP, '0.0.0.0', 50267)
2018-12-24T23:08:05+0800 [-] Announcer starting on 60497
2018-12-24T23:08:05+0800 [-] Starting protocol <recceiver.announce.Announcer object at 0x108624320>
```
